# Generated by Django 3.0.6 on 2020-06-16 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_auto_20200615_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(upload_to='rooms_photos'),
        ),
    ]
